- .github/workflows/assemble-distro.yml
- .gitignore
This action is invoked when new changes are pushed to the `main` branch, or new tags are created. It then assembles the package distribution tarballs, and uploads it to the given tag, or (in the case of pushes to `main`) to the tag `latest` (this tag then is also changed to point to the new HEAD of `main`)
> Add assemble-distro.yml

- .github/workflows/scan-for-updates.yml
This reverts commit 94156496cd6281055393e084d02b38dea3f9120f.
Unfortunately we also need the JSON package and that is not
installed by the Ubuntu package by default.
All of this would not be necessary if we just had our own
container
Hopefully fixes #153
> Revert "scan-for-updates: install GAP via apt-get"

- .github/workflows/pull-request.yml
- .github/workflows/test-all.yml
Status of "failing" package tests: I've moved this overview [to an issue of its own](https://github.com/gap-system/PackageDistro/issues/155), so that I can merge this PR.
> Experiment with testing package distro

- .github/workflows/pull-request.yml
First, a wrong path was used (lacking the 'packages/' prefix). Second,
the correct git plumbing command is 'cat-files', not 'show', which has
the wrong semantics
> Fix code for obtaining old metadata

- tools/scan_for_updates.py
This was modified when we merged the tools repository. But it was only
needed due to a minor mistake in the conversion of 'add_sha256_to_json'.
The latter was fixed in d76a56a867267405e2d4903cc7c1204eba4517c8, so it
should be safe to restore this code, too
> Once again only write pkginfo.g files when the hash is new

- .github/workflows/test-all.yml
Resolves #162
Still need to test if this helps at all...
UPDATE: It does help! The two changes in this PR made `test-all.yml` go from [~15 minutes](https://github.com/fingolfin/PackageDistro/actions/runs/1990136196) to [~6 minutes](https://github.com/fingolfin/PackageDistro/actions/runs/1990220386) with a "hot cache".
> Use ccache to speed up compilation; switch gap.tar.gz to gap.tar.zst (smaller, yet created faster)

- .github/workflows/tools-tests.yml
- packages/fining/meta.json
- tools/scan_for_updates.py
... instead of assuming they are UTF-8 encoded and "decoding" them.
While most PackageInfo.g these days are either pure ASCII or use UTF-8
encoding, this is not true for all of them. But by changing the
encoding, we get a false validation error once we compare the file
against its twin in the package archive.
> Download byte exact copies of PackageInfo.g files

- tools/scan_for_updates.py
- tools/validate_package.py
- fix bug that caused the GAP part of the validation to not be invoked anymore
- changed `gap_exec` helper to not suppress GAP output completely anymore,
so that we can see the output of GAP's `ValidatePackageInfo` function
- add basic validation for tarballs (resolves #166)
> Improve package validation

- packages/matgrp/meta.json
The new version requires GAP 4.12, which is not yet released
> Downgrade matgrp

- packages/cap/meta.json
- packages/linearalgebraforcap/meta.json
This two packages have changes that require the two updates to happen simultaneously.
Closes #229. Closes #230.
> Update linearalgebraforcap to 2022.03-04, cap to 2022.03-06

- tools/scan_for_updates.py
- tools/tests/test_scan_for_updates.py
- tools/validate_package.py
Directly pipe input into the GAP process, instead of doing it indirectly
via `echo`. This allows us to completely avoid shell quoting issues.
Moreover, capture the output of the GAP process, so that in the future
we can e.g. let GAP print JSON to stdout and parse that in Python.
> tools: refactor gap_exec

- .github/workflows/test-all.yml
- packages/linearalgebraforcap/meta.json
- packages/matgrp/meta.json
This patch is an attempt to resolve random crashes we have been seeing in CI
whenever digraphs and/or semigroups are loaded. The theory is that this is
caused by their use of `-march=native`, combined with the fact that we use
`ccache`, yet the results run on different VMs. So perhaps one day a binary is
compiled on one computer, and put into the cache; then another day the same
file is compiled again but on a different computer, and the compilation result
is retrieved from the cache. But since the computer has a different CPU, the
binary does not actually run there due to its use of `-march=native`.
Time will tell if this helps or not...
> Fix crashes in digraphs and semigroups (hopefully)

- .github/workflows/pull-request.yml
- packages/cap/meta.json
... unfortunately this won't work for PRs that come from forks... but for now let's try to at least make it work for "internal" PRs...
Note that https://github.com/marketplace/actions/create-or-update-comment suggests it might be possible to use a `pull_request_target` trigger, but I am not yet sure how we'd possibly do that
> Add PR comments with status reports (WIP)

- .github/workflows/test-all.yml
So far we tested that package updates don't break other packages -- but we
did not actually test if they broke GAP's own test suite. So let's change that...
Unfortunately the test suite *is* broken right now, so that has to be fixed first...
> Run test suite as part of PR CI

- packages/cap/meta.json
- packages/linearalgebraforcap/meta.json
- packages/modulepresentationsforcap/meta.json
- [modulepresentationsforcap] Update to 2022.05-02 closes #366
- [linearalgebraforcap] Update to 2022.05-03 closes #367
- [cap] Update to 2022.05-05 closes #365
> CAP related package updates

- .github/workflows/test-all.yml
- tools/gather_dependencies.py
Thanks to ccache it shouldn't be too bad...
This patch was in there before and reverted because it lead to nconvex crashing. Hopefully not so anymore...
Resolves #285
> Let NormalizInterface build Normaliz

- tools/download_packages.py
- tools/scan_for_updates.py
- tools/tests/test_download_packages.py
- tools/tests/test_scan_for_updates.py
- tools/utils.py
- tools/validate_package.py
- `download_archive` now calls `utils.download` and does not attempt to retry; this simplifies the logic, and I think just rerunning whatever command lead to the error may be the better strategy. Alas, time will tell, we can re-evaluate this should we encounter problems due to temporary download failures too frequently
- moved `download_to_memory` to `utils`
- `download` and `download_to_memory` now raise an exception if the download failed, e.g. with a 404 "file not found" HTTP error
- ...
> Refactor download related code

- tools/validate_package.py
These often cause trouble on Windows.
If anyone ever really needs symlinks, we could relax this, but
at the very least we should prevent symlinks pointing outside
the package directory.
> Forbid symlinks in package tarballs

- tools/utils.py
While importing new package, if only `_archives` directory does not exists, the import wrongly fails.
```
gap-packagedistro on  main λ ./tools/import_packages.py https://limakzi.github.io/smallantimagmas/PackageInfo.g
downloading https://limakzi.github.io/smallantimagmas/PackageInfo.g to tempfile /tmp/pkginfouja6h7cs.g
update packages/smallantimagmas/meta.json
gap-packagedistro on  main λ rm -rvf _archives/
removed '_archives/smallantimagmas-0.2.3.tar.gz'
removed directory '_archives/'
gap-packagedistro on  main λ ./tools/import_packages.py https://limakzi.github.io/smallantimagmas/PackageInfo.g
downloading https://limakzi.github.io/smallantimagmas/PackageInfo.g to tempfile /tmp/pkginfoh_kpnblo.g
Traceback (most recent call last):
File …
```
> fix: Fix _archives creation

- .github/workflows/test-all.yml
Don't delete `build/ffdata.h` and `build/version.h` as PackageManager needs them to build GAP packages with kernel extensions.
This was a latent bug since 2022, but it was obscured by PackageManager and GAP library behaviour (e.g. installing  e.g. `io` was skipped because it was already installed and workable anyway). Both are stricter now (which is good), and so this bug in the PackageDistro setup was revealed.
Fixes https://github.com/gap-system/gap/issues/5916
CC @mtorpey @lgoettgens @ThomasBreuer
> Fix bug that caused failures in `PackageManager` tests

- .github/workflows/assemble-distro.yml
- .github/workflows/pull-request.yml
- .github/workflows/scan-for-updates.yml
- .github/workflows/test-all.yml
- .github/workflows/tools-tests.yml
- .github/workflows/update-latest-report.yml
The github-runner for `ubuntu-20.04` [will completely stop working on April 15](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes), and the workflows of this repo [have previously been impacted by scheduled brownouts](https://github.com/gap-system/PackageDistro/actions/runs/14342630620).
This PR updates the workflows to use `ubuntu-latest`, though `ubuntu-22.04` or `ubuntu-24.04` could also be used of course.
> Update ubuntu-20.04 to ubuntu-latest in workflows
