gap-system/PackageDistro

.github/workflows/assemble-distro.yml, .github/workflows/scan-for-updates.yml
Now caches are updated correctly, and outdated archives are removed
Resolves #14 
Resolves #22
=> Revise cache handling

.github/workflows/scan-for-updates.yml
=> Use GitHub App so workflows are run on generated PRs

.github/workflows/scan-for-updates.yml
Also remove debug restriction on how many PRs are created
=> Activate scan-for-updates cron job

.github/workflows/pull-request.yml, .github/workflows/test-all.yml
This now performs some initial validation and then delegates to `test-all`
for the rest.
=> Revise CI tests for pull requests

tools/scan_for_updates.g, tools/scan_for_updates.py, tools/tests/test_scan_for_updates.py
- refactor scan_for_updates.py
- scan_for_updates.py: always re-download package tarballs
Resolves #186
=> refactor `scan_for_updates.py`; always re-download package tarballs

.github/workflows/assemble-distro.yml
... by using the 'paths' selector for 'push' event to replace the first job
=> assemble-distro.yml: simplify

.github/workflows/pull-request.yml, .github/workflows/test-all.yml
=> Add code to also run test-all against GAP 4.11.1 (the latest release)

.github/workflows/test-all.yml
=> `test-all.yml`: allow restricting which packages are built resp. tested

.github/workflows/test-all.yml, packages/digraphs/meta.json
- Workaround atlasrep / ctbllib failures (closes #233)
- <s>Workaround test failures caused by missing GAP deps</s> (this one needs more work)
- [digraphs] Update to 1.5.1 (closes #235)
I need to modify some package in order to the test first two changes...
=> Combine <s>three</s>two other PRs

.github/workflows/tools-tests.yml, tools/gather_dependencies.py, tools/generate_test_status.py, tools/scan_for_updates.py
That's the python installed on GH runners by default
=> tools: restore compat with Python 3.8

.github/workflows/test-all.yml
Thanks to @ThomasBreuer for explaining to me what is needed. Let's see if this works as intended.
=> Workaround ctbllib hang with OnlyNeeded

tools/scan_for_updates.py, tools/tests/test_scan_for_updates.py, tools/validate_package.py
=> Validate PackageInfoURL and README_URL

tools/validate_package.py
=> tools: restrict 'Status' field to 'accepted' or 'deposited'

.github/workflows/test-all.yml, packages/ace/meta.json
Thanks to ccache it shouldn't be too bad...
=> Let NormalizInterface build Normaliz

.github/workflows/update-latest-report.yml, tools/generate_report.py, tools/generate_test_status.py
Close #282
- Add `which_gap` to test-status.json and report.md header.
- Add `which_gap` to automated commit message.
=> Improve Reports

.github/workflows/test-all-and-report.yml, .github/workflows/test-all.yml, tools/generate_report.py, tools/generate_test_status.py
Apply open suggestion from #296
Additionaly, remove hack since script war already executed multiple times on this repo.
=> Add comments for hardcoded names in generate_test_status.py.

tools/update_latest_report.py
- move some code into functions (should be done with more)
- change the redirect HTML files to contain valid HTML
=> Refactor update_latest_report.py

README.md
=> Document how to add or modify packages

.github/workflows/pull-request.yml
=> Skip PR tests if 'skip tests' label is set

.github/workflows/test-all.yml
- Workaround YangBaxter test failures
- HACK to trigger CI
=> yangbaxter workaround

packages/cap/meta.json, packages/monoidalcategories/meta.json
- [cap] Update to 2022.08-05 closes #481 
- [monoidalcategories] Update to 2022.08-03 closes #480
=> Update CAP and MonoidalCategories

.github/workflows/test-all.yml, packages/gapdoc/meta.json, tools/gather_dependencies.py
=> Update GAPDoc to 1.6.6, workarounds

.github/workflows/pull-request.yml, .github/workflows/scan-for-updates.yml, .github/workflows/test-all.yml
=> CI: replace obsolete set-output

tools/validate_package.g
=> Reject package updates without License field

tools/assemble_distro.py
=> Avoid encoding mtime into package-infos.json.gz

.github/workflows/test-all.yml
Testing at https://github.com/gap-system/PackageDistro/actions/runs/7604428542  ...
=> Support slashes in branch names

README.md
As we learned recently, the 'manual' submission of packages via a
self-created PRs is not optimally supported and lacks some
features, so let's not advertise it anymore. Also clarify some
other points.
=> README: tweak submission guidelines

tools/assemble_distro.py, tools/gather_dependencies.py
=> hap: add imagemagick as a dependency

tools/gather_dependencies.py
As suggested in https://github.com/gap-system/PackageDistro/pull/1221#issuecomment-3309266115.
=> Also gather dependencies from package extensions
